AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PoC client for the Oauth Service

##########################################################################
#  Parameters                                                            #
##########################################################################
Parameters:
  StageName:
    Type: String
    Default: test

##########################################################################
#  Global values that are applied to all resources                       #
##########################################################################
Globals:
  Function:
    MemorySize: 256
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 29
    Environment:
      Variables:
        RUST_BACKTRACE: 1
        RUST_LOG: info

Resources:
  MyProtectedApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: test
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionArn: !GetAtt AppLambdaAuthorizerFunction.Arn
            FunctionInvokeRole: !GetAtt AppLambdaAuthorizerFunctionRole.Arn
            Identity:
              Context:
                - httpMethod
                - resourceId
              Headers:
                - Authorization
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true

  AppApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/app-random-api
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyProtectedApi
            Path: /random-api
            Method: GET
            PayloadFormatVersion: "2.0"
      Tags:
        Name: random-api
        env: !Ref StageName
        service: app
  
  AppApiFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${AppApiFunction}"

  AppLambdaAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/app-lambda-authorizer
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Name: jwt-authorizer
        env: !Ref StageName
        service: app
  
  AppLambdaAuthorizerFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${AppLambdaAuthorizerFunction}"

  AppAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/app-auth
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
           OAUTH_TOKEN_URL: !Sub ['${filename}token', filename: !ImportValue oauth-AuthUrl]
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth
            Method: GET
      Tags:
        Name: auth
        env: !Ref StageName
        service: app
  
  AppAuthFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${AppAuthFunction}"
  
  AppLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/app-login
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          REDIRECT_PATH: "/auth"
          OAUTH_AUTHORIZE_URL: !Sub ['${filename}authorize', filename: !ImportValue oauth-AuthUrl]
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /login
            Method: GET
      Tags:
        Name: login
        env: !Ref StageName
        service: app

  AppLoginFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${AppLoginFunction}"

Outputs:
  ProtectedEndpoint:
    Description: The default endpoint for the HTTP API.
    Value: !GetAtt MyProtectedApi.ApiEndpoint
  AppUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: 
        Fn::Sub: ${AWS::StackName}-AppUrl
